name: AuthPlayer
main: archangel.authplayer.AuthPlayer
version: 1.2
description: Provides alternate login when minecraft.net login servers are down.
authors: [Arcalyth, Thulinma]

commands:
    auth:
        description: AuthPlayer account maintenance command.
        usage: |
            /auth <username> <password> - Log into or create an account (as guest).
            /auth <password> - Create an account (as premium user).
            /auth list - List registered players.
            /auth delete <username> - Delete a registered player.
            /auth password <new password> - Change your password.
            /auth create <username> <password> - Create a new account for somebody else.